### ISSUE TITLE
touchid not defined

### ISSUE THREAD

**Issue by gigocabrera** [leecrossley/cordova-plugin-touchid#17]
Hi, 
I'm getting the following error in an ionic2/angular2 app in the console in Chrome dev tools. However, when I install the app on my iPhone 6, the TouchID functionality seems to be working fine. 

![touchid_exception](https://cloud.githubusercontent.com/assets/6364855/17123141/78dfeaaa-52af-11e6-8490-45204c5b144e.png)

Here's the code I'm using:

https://github.com/gigocabrera/MoneyLeash2/blob/11b864a33bff56ef200cd5d9d3cff033d5035699/app/app.ts#L94

Any thoughts?

**Comment by jsanta** [comment]
Hi.
Did you install the plugin using the git url as reference or just ran 
`ionic plugin add cordova-plugin-touchid` ?
Just faced the same problem and figured that the 3.2.0 version installed by using cordova-plugin-touchid instead of https://github.com/leecrossley/cordova-plugin-touchid was causing the problem.

Installed the plugin by running: 
`cordova plugin add https://github.com/leecrossley/cordova-plugin-touchid.git`
and everything  worked again.
